[package]
name = "pwd_from_stdin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pwd_from_stdin"
path = "src/bin/main.rs"

[dependencies]
itertools = "0.10.3"
rand = "0.8.5"
