name: MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  Build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install libsvm
      run: brew install libsvm
    - name: Build
      run: LIBSVM_INCLUDE="$(brew --prefix libsvm)/include" LIBSVM_LIBRARY="$(brew --prefix libsvm)/lib" cargo build
    - name: Run tests
      run: cargo test --verbose
