name: MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  LIBSVM_PATH: /usr/local/
  
jobs:
  Build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install libsvm
      run: brew install libsvm && brew link libsvm
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose
